import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/homepage">HomePage</Link>
        </li>
        <li>
          <Link to="/loginpage">LoginPage</Link>
        </li>
        <li>
          <Link to="/registerpage">RegisterPage</Link>
        </li>
        <li>
          <Link to="/forgotpassword">ForgotPassword</Link>
        </li>
        <li>
          <Link to="/verifyemail">VerifyEmail</Link>
        </li>
        <li>
          <Link to="/emailaddressverifiedsuccessfully">
            EmailAddressVerifiedSuccessfully
          </Link>
        </li>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/profilescreen">ProfileScreen</Link>
        </li>
        <li>
          <Link to="/userjournalcollectionscreen">
            UserJournalCollectionScreen
          </Link>
        </li>
        <li>
          <Link to="/userjourneyentry">UserJourneyEntry</Link>
        </li>
        <li>
          <Link to="/tradestrategyloggerscreen">TradeStrategyLoggerScreen</Link>
        </li>
        <li>
          <Link to="/performancebenchmarkscreenone">
            PerformanceBenchmarkScreenOne
          </Link>
        </li>
        <li>
          <Link to="/riskassessmentscreen">RiskAssessmentScreen</Link>
        </li>
        <li>
          <Link to="/manualtradeimport">ManualTradeImport</Link>
        </li>
        <li>
          <Link to="/performancebenchmarkscreen">
            PerformanceBenchmarkScreen
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
